Soccer_Care/Areas/Admin/Controllers/ManageUserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using NuGet.Protocol;
using Soccer_Care.Models;

namespace Soccer_Care.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class ManageUserController : Controller
    {

        SoccerCareDbContext _context;
        IWebHostEnvironment webHostEnvironment;
        UserManager<UserModel> _userManager;
        RoleManager<IdentityRole> _roleManager;
        public ManageUserController(SoccerCareDbContext _soccer , IWebHostEnvironment webHostEnvironment, UserManager<UserModel> userManager ,RoleManager<IdentityRole> roleManager)
        {
            _context = _soccer;
            this.webHostEnvironment = webHostEnvironment;
            _userManager = userManager;
            _roleManager = roleManager;
        }
        public async Task<IActionResult> EditUser(string Id)
        {
            List<IdentityRole> listRole = _roleManager.Roles.ToList();
            var findUser = await _userManager.FindByIdAsync(Id);
            string role = "";
            foreach(IdentityRole r in listRole)
            {
                if (await _userManager.IsInRoleAsync(findUser, r.Name))
                {
                    role = r.Name;
                    break;
                }
            }
            ViewBag.ListRole = listRole;
            ViewBag.CurrentRole = role;
            if (findUser == null)
            {
                return NotFound();
            }
            return View(findUser);
        }
        [HttpPost]
        public async Task<IActionResult> ConfirmEditUser(UserModel user, IFormFile NewImage, string role)
        {
            var findUser = _userManager.FindByIdAsync(user.Id);
            if (NewImage != null)
            {
                var getPath = Path.Combine(webHostEnvironment.WebRootPath, "images");
                string extension = Path.GetExtension(NewImage.FileName);
                var saveImg = Path.Combine(getPath, user.Id + extension);
                using (var fileStream = new FileStream(saveImg, FileMode.Create))
                {
                    NewImage.CopyTo(fileStream);
                    findUser.Result.AvatarURL = user.Id + extension;
                }
            }
            findUser.Result.FullName = user.FullName;
            findUser.Result.PhoneNumber = user.PhoneNumber;
            findUser.Result.IsBlock = user.IsBlock;
            var result = await _userManager.UpdateAsync(findUser.Result);
            if (result.Succeeded)
            {
                var userRoles = await _userManager.GetRolesAsync(findUser.Result);
                await _userManager.RemoveFromRolesAsync(findUser.Result, userRoles);
                await _userManager.AddToRoleAsync(findUser.Result, role);
                return RedirectToAction("ManageUser", "Admin");
            }
            
            return NotFound();
        }
    }
}

Soccer_Care/Areas/Admin/Controllers/PitchController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Newtonsoft.Json;
using Soccer_Care.Models;
using System.Collections.Generic;
using System.Data.Entity;
using System.Security.Authentication;
using static System.Reflection.Metadata.BlobBuilder;

namespace Soccer_Care.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin,Partner")]
    public class PitchController : Controller
    {

        private readonly SoccerCareDbContext _context;
        private readonly UserManager<UserModel> _userManager;
        IWebHostEnvironment env;
        public PitchController(SoccerCareDbContext context, UserManager<UserModel> userManager, IWebHostEnvironment env)
        {
            _context = context;
            _userManager = userManager;
            this.env = env;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.TypeField = JsonConvert.SerializeObject(_context.TypeFields.ToList());
           
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(FootBallFieldModel football, string city, string district, string street, IFormFile ImageFile)
        {
            string address = street + "," + district + "," + city;
            football.IDUserOwner = _userManager.FindByEmailAsync(football.Username).Result.Id;
            football.Address = address;
            football.IDFootBallField = Guid.NewGuid().ToString();
            if (ImageFile != null)
            {
                var folderPath = Path.Combine(env.WebRootPath, "images");
                var getExtension = Path.GetExtension(ImageFile.FileName);
                var ImagePath = Path.Combine(folderPath, football.IDFootBallField + getExtension);
                using (var fileStream = new FileStream(ImagePath, FileMode.Create))
                {
                    ImageFile.CopyTo(fileStream);
                    football.HinhAnhDaiDien = football.IDFootBallField + getExtension;
                }
            }else
            {
                football.HinhAnhDaiDien = "no_img";
            }
            if(!ModelState.IsValid)
            {
                float minPrice = 9999999;
                foreach (ListFieldModel list in football.ListField){
                    list.IDField = Guid.NewGuid().ToString();
                    list.IDFootballField = football.IDFootBallField;
                    if (list.Gia < minPrice) minPrice = list.Gia;
                    if (list.FileImage != null)
                    {
                        var FolderPath = Path.Combine(env.WebRootPath, "images");
                        var GetExtension = Path.GetExtension(list.FileImage.FileName);
                        var ImagePath = Path.Combine(FolderPath, list.IDField + GetExtension);
                        using (var fileStream = new FileStream(ImagePath, FileMode.Create))
                        {
                            list.FileImage.CopyTo(fileStream);
                            list.HinhAnhSanBong = list.IDField + GetExtension;
                        }
                    }
                    else
                    {
                        list.HinhAnhSanBong = "no_img";
                    }
                    _context.listFields.Add(list);                   
                }
                football.Gia = minPrice;
                _context.FootBallFields.Add(football);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Admin");
            }
            return View(football);
        }

        [HttpGet]
        public IActionResult Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var pitch = _context.FootBallFields.FirstOrDefault(u => id == u.IDFootBallField);
            if (pitch == null)
            {
                return NotFound();
            }
            return View(pitch);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirm(string id)
        {
            var pitch = await _context.FootBallFields.FindAsync(id);
            pitch.isDisable = 1;
            _context.FootBallFields.Update(pitch);
            await _context.SaveChangesAsync();
            return RedirectToAction("ManagePitch","Admin");
        }

        public ActionResult Edit(string id)
        {
            if(id == null)
            {
                return NotFound();
            }
            var pitch = _context.FootBallFields.FirstOrDefault(u => id == u.IDFootBallField);
            if (pitch == null)
            {
                return NotFound();
            }
            ViewBag.GetType = _context.TypeFields.ToList();
            ViewBag.ListField = _context.listFields.Where(i => i.IDFootballField == id).ToList();   
            return View(pitch);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(FootBallFieldModel footBall, IFormFile ImageFile)
        {
            try
            {
                var editField = _context.FootBallFields.FirstOrDefault(i => i.IDFootBallField == footBall.IDFootBallField);
                if (ImageFile != null)
                {
                    var FolderPath = Path.Combine(env.WebRootPath, "images");
                    var GetExtension = Path.GetExtension(ImageFile.FileName);
                    var ImagePath = Path.Combine(FolderPath, editField.IDFootBallField + GetExtension);
                    using (var fileStream = new FileStream(ImagePath, FileMode.Create))
                    {
                        ImageFile.CopyTo(fileStream);
                        editField.HinhAnhDaiDien = editField.IDFootBallField + GetExtension;
                    }
                }
                editField.Address = footBall.Address;
                editField.Gia = footBall.Gia; 
                editField.Name = footBall.Name;
                _context.FootBallFields.Update(editField);
                _context.SaveChanges();
                return RedirectToAction("ManagePitch","Admin");
            }
            catch
            {
                return View();
            }
        }
        //Mini field
        public IActionResult EditChildField(string id)
        {
            var find = _context.listFields.FirstOrDefault(i => i.IDField == id);
            if (find != null) return PartialView("EditChildField", find);
            return NotFound();
        }

        [HttpPost]
        public IActionResult ConfirmEditChildField(ListFieldModel listField, IFormFile ImageFile)
        {
            TempData["EditSuccess"] = "Đã cập nhật thành công";
            var getImg = _context.listFields.FirstOrDefault(i => i.IDField == listField.IDField);
            if (ImageFile != null)
            {
                var FolderPath = Path.Combine(env.WebRootPath, "images");
                var GetExtension = Path.GetExtension(ImageFile.FileName);
                var ImagePath = Path.Combine(FolderPath, listField.IDField + GetExtension);
                using (var fileStream = new FileStream(ImagePath, FileMode.Create))
                {
                    ImageFile.CopyTo(fileStream);
                    listField.HinhAnhSanBong = listField.IDField + GetExtension;
                }
            }else
            {
                listField.HinhAnhSanBong = getImg.HinhAnhSanBong;
            }
            _context.listFields.Update(listField);
            _context.SaveChangesAsync();
            return RedirectToAction("ManagePitch", "Admin", TempData["EditSuccess"]);
        }
        public IActionResult DeleteChildField(string id)
        {
            var find = _context.listFields.FirstOrDefault(i => i.IDField == id);
            if (find != null) return PartialView("DeleteChildField", find);
            return NotFound();
        }
        [HttpPost]
        public IActionResult ConfirmDeleteChildField(string id)
        {
            var find = _context.listFields.FirstOrDefault(i => i.IDField == id);
            if (find != null)
            {
                find.isDisable = 1;
                _context.listFields.Update(find);
                _context.SaveChangesAsync();
                return RedirectToAction("ManagePitch", "Admin", TempData["EditSuccess"]);
            }
            return NotFound();
        }
    }
}

Soccer_Care/Areas/Admin/Views/Admin/GetExactDate.cshtml
<div id="displayUser">
    <div class="col-12 tm-block-col">
        <div class="tm-bg-primary-dark tm-block tm-block-taller tm-block-scroll">
            <h2 class="tm-block-title">Danh sách người dùng đặt sân</h2>
            <input type="date" id="getUserOrderDate" class="tm-block-settings" placeholder="@DateTime.Now" />
            <div id="tableContent">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Mã đặt sân.</th>
                            <th scope="col">Tên Sân</th>
                            <th scope="col">Số điện thoại</th>
                            <th scope="col">Tên người đặt</th>
                            <th scope="col">Ngày đặt</th>
                            <th scope="col">Giờ Đặt</th>
                            <th scope="col">Thanh Toán</th>
                            <th scope="col">Trạng Thái</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (DetailsOrderModel detailsOrderModel in Model)
                        {
                            <tr>
                                <th scope="row"><b>@detailsOrderModel.IDDetails</b></th>
                                <td>@detailsOrderModel.Order.FootBall.Name | @detailsOrderModel.Order.ListField.NameField</td>

                                @if (detailsOrderModel.Order != null)
                                {
                                    <td>@detailsOrderModel.Order.SoDienThoai</td>
                                }
                                <td>@detailsOrderModel.Order.User.FullName</td>
                                <td>@detailsOrderModel.DateTime.ToString("dd/MM/yyyy")</td>
                                <td>@detailsOrderModel.StartTime</td>
                                @if (detailsOrderModel.isThanhToan == 1)
                                {

                                    <td>
                                        <div class="tm-status-circle moving">
                                        </div>Thanh Toán VNPAY
                                    </td>
                                }
                                else
                                {
                                    <td>
                                        <div class="tm-status-circle pending">
                                        </div>Thanh Toán Tại Sân
                                    </td>
                                }
                                @if (detailsOrderModel.Status == "Đang Đến")
                                {
                                    <td>
                                        <select class="confirmUser">
                                            <option value="Đang Đến" selected>Đang Đến</option>
                                            <option value="Đã Đến">Đã Đến</option>
                                            <option value="Đã Hủy">Đã Hủy</option>
                                        </select>
                                        <input data-idorder="@detailsOrderModel.IDOrder" hidden>
                                    </td>
                                }
                                else
                                {
                                    <td>@detailsOrderModel.Status</td>
                                }
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="/admin_folder/js/moment.min.js"></script>
<script src="/admin_folder/js/Chart.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="/admin_folder/js/bootstrap.min.js"></script>
<script src="/admin_folder/js/tooplate-scripts.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $.ajax({
            type: "GET",
            url: "/Admin/Admin/GetTotals",
            data: "",
            contextType: "aplication/json, charset=utf8",
            dataType: "json",
            success: OnSuccess,
        });
        function OnSuccess(data) {
            const barChart = document.getElementById('myChart');
            var _data = data;
            var _labels = _data[0];
            var _chartData = _data[1];
            var colors = ['Blue'];
            new Chart(barChart, {
                type: 'bar',
                data: {
                    labels: _labels,
                    datasets: [{
                        label: 'Doanh thu hôm nay', backgroundColor: colors, data: [_chartData], borderWidth: 2
                    }]
                }
            });
        }
        $(".confirmUser").change(function () {
            var selectedValue = $(this).val();
            var getID = $(this).siblings("input[data-idorder]").data('idorder');
            $.ajax({
                url: '/Admin/Admin/UpdateStatus',
                type: 'GET',
                data: { id: getID, value: selectedValue },
                success: function (data) {
                    $("#tableContent").html(data);
                    if (selectValue == "Đã Đến") {
                        $.ajax({
                            type: "GET",
                            url: "/Admin/Admin/GetTotals",
                            data: "",
                            contextType: "aplication/json, charset=utf8",
                            dataType: "json",
                            success: OnSuccess,
                        });
                        $.ajax({
                            type: "GET",
                            url: "/Admin/Admin/GetTotalsOfMonth",
                            data: "",
                            contextType: "aplication/json, charset=utf8",
                            dataType: "json",
                            success: OnSuccess2,
                        });
                    }
                },
                error: function (xhr) {
                    alert(xhr.response);
                }
            })
        });
        $.ajax({
            type: "GET",
            url: "/Admin/Admin/GetTotalsOfMonth",
            data: "",
            contextType: "aplication/json, charset=utf8",
            dataType: "json",
            success: OnSuccess2,
        });
        function OnSuccess2(data) {
            const barChart = document.getElementById('lineChart');
            var _data = data;
            var _labels = _data[0];
            var _chartData = _data[1];
            new Chart(barChart, {
                type: 'line',
                data: {
                    labels: _labels,
                    datasets: [{
                        label: 'Doanh thu tháng này',
                        data: _chartData,
                        fill: false,
                        borderColor: 'rgb(75, 192, 192)',
                        tension: 0.1
                    }]
                }
            });
        }
        $("#getUserOrderDate").change(function () {
            var selectedValue = $(this).val();
            $.ajax({
                url: '/Admin/Admin/GetExactDate',
                type: 'GET', 
                date: {date: selectedValue},
                success: function (data) {
                    $("#tableContent").html(data);
                },
                error: function (xhr) {
                    alert(xhr.response);
                }
            });
        });
    });
</script>

Soccer_Care/Areas/Admin/Views/Admin/ManagePitch.cshtml
@model IEnumerable<Soccer_Care.Models.FootBallFieldModel>
@{
    ViewData["Title"] = "ManagePitch";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div class="container mt-5">
    <div class="row tm-content-row">
        <div class="col-sm-12 col-md-12 col-lg-8 col-xl-8 tm-block-col">
            <div class="tm-bg-primary-dark tm-block tm-block-products">
                <div class="tm-product-table-container">
                    <table class="table table-hover tm-table-small tm-product-table">
                        <thead>
                            <tr>
                                <th scope="col">NAME</th>
                                <th scope="col">Address</th>
                                <th scope="col">Price</th>
                                <th scope="col">&nbsp;</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach(var item in Model)
                            {
                                @if (item.isDisable == 0)
                                {
                                    <tr>
                                        <td class="tm-product-name">@item.Name</td>
                                        <td>@item.Address</td>
                                        <td>@item.Gia</td>
                                        <td>
                                            <a asp-action="Delete" asp-controller="Pitch" asp-area="Admin" asp-route-id="@item.IDFootBallField" class="tm-product-delete-link">
                                                <i class="far fa-trash-alt tm-product-delete-icon"></i>
                                            </a>
                                            <a asp-action="Edit" asp-controller="Pitch" asp-area="Admin" asp-route-id="@item.IDFootBallField" class="tm-product-delete-link">
                                                <i class="far fa-edit tm-product-delete-icon"></i>
                                            </a>
                                        </td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>
                <!-- table container -->
                <a asp-controller="Pitch" asp-action="Create" asp-area="Admin" class="btn btn-primary btn-block text-uppercase mb-3">Add new field</a>
            </div>
        </div>
    </div>
</div>

Soccer_Care/Areas/Admin/Views/Admin/ManageUser.cshtml
@using Microsoft.AspNetCore.Identity;
@model List<UserModel>
@{
    ViewData["Title"] = "ManageUser";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div class="container mt-5">
    <div class="row tm-content-row">
        <div class="col-12 tm-block-col">
            <form asp-action="SearchUser" class="tm-bg-primary-dark tm-block tm-block-h-auto">
                <h2 class="tm-block-title">Tìm User theo quyền </h2>
                <p class="text-white">Vai trò</p>
                <select name="IDRole" class="custom-select">
                    @foreach(IdentityRole role in ViewBag.ListType)
                    {
                        if (role.Name == ViewBag.RoleID)
                        {
                            <option value="@role.Name" selected>@role.Name</option>
                        }else
                        {
                            <option value="@role.Name">@role.Name</option>
                        }
                    }
                </select>
                <input type="submit" class="btn btn-primary mt-2" />
            </form>
        </div>
        <div class="col-12 tm-block-col">
            <table class="table table-hover tm-table-small tm-product-table">
                <thead>
                    <tr>
                        <th scope="col">Username</th>
                        <th scope="col">Full name</th>
                        <th scope="col">Phone number</th>
                        <th scope="col">Avatar</th>
                        <th scope="col">&nbsp;</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.UserName</td>
                            <td>@item.FullName</td>
                            <td>@item.PhoneNumber</td>
                            <td>
                                <img src="/images/@item.AvatarURL" height="100" width="100">
                            </td>
                            <td>
                                <a asp-action="Delete" asp-controller="Pitch" asp-area="Admin" asp-route-id="@item.Id" class="tm-product-delete-link">
                                    <i class="far fa-trash-alt tm-product-delete-icon"></i>
                                </a>
                                <a asp-area="Admin" asp-controller="ManageUser" asp-action="EditUser" asp-route-id="@item.Id" class="tm-product-delete-link">
                                    <i class="far fa-edit tm-product-delete-icon"></i>
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

Soccer_Care/Areas/Admin/Views/Admin/UpdateStatus.cshtml
@model List<DetailsOrderModel>
<table class="table">
    <thead>
        <tr>
            <th scope="col">Mã đặt sân.</th>
            <th scope="col">Tên Sân</th>
            <th scope="col">Số điện thoại</th>
            <th scope="col">Tên người đặt</th>
            <th scope="col">Ngày đặt</th>
            <th scope="col">Giờ Đặt</th>
            <th scope="col">Thanh Toán</th>
            <th scope="col">Trạng Thái</th>
        </tr>
    </thead>
    <tbody>

        @foreach (DetailsOrderModel detailsOrderModel in Model)
        {
            <tr>
                <th scope="row"><b>@detailsOrderModel.IDDetails</b></th>
                <td>@detailsOrderModel.Order.FootBall.Name | @detailsOrderModel.Order.ListField.NameField</td>

                @if (detailsOrderModel.Order != null)
                {
                    <td>@detailsOrderModel.Order.SoDienThoai</td>
                }
                <td>@detailsOrderModel.Order.User.FullName</td>
                <td>@detailsOrderModel.DateTime.ToString("dd/MM/yyyy")</td>
                <td>@detailsOrderModel.StartTime</td>
                @if (detailsOrderModel.isThanhToan == 1)
                {

                    <td>
                        <div class="tm-status-circle moving">
                        </div>Thanh Toán VNPAY
                    </td>
                }
                else
                {
                    <td>
                        <div class="tm-status-circle pending">
                        </div>Thanh Toán Tại Sân
                    </td>
                }
                @if (detailsOrderModel.Status == "Đang Đến")
                {
                    <td>
                        <select class="confirmUser">
                            <option value="Đang Đến" selected>Đang Đến</option>
                            <option value="Đã Đến">Đã Đến</option>
                            <option value="Đã Hủy">Đã Đến</option>
                        </select>
                    </td>
                }
                else
                {
                    <td>@detailsOrderModel.Status</td>
                }
            </tr>
        }
    </tbody>
</table>