Soccer_Care/Controllers/ContactController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Net;
using System.Net.Mail;

namespace Soccer_Care.Controllers
{
    [Authorize(Roles = "Admin,Partner,User")]
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Test()
        {
            return View();
        }
        
    }
}

Soccer_Care/Controllers/PitchBallController.cs
using Humanizer;
using Humanizer.Bytes;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Soccer_Care.Models;
using Soccer_Care.Services;
using System.Reflection.Metadata;
using System.Xml.Linq;


namespace Soccer_Care.Controllers
{

    public class PitchBallController : Controller
    {
        IHttpContextAccessor contextAccessor;
        private readonly SoccerCareDbContext _context;
        private readonly UserManager<UserModel> _userManager;
        private readonly IVnPayService _vnPayService;
        public PitchBallController(IHttpContextAccessor contextAccessor, SoccerCareDbContext context, UserManager<UserModel> userManager, IVnPayService vnPayService) {
            this.contextAccessor = contextAccessor;
            this._context = context;
            this._userManager = userManager;
            _vnPayService = vnPayService;
        }
        public IActionResult Index()
        {
            if (contextAccessor.HttpContext.Session.GetString("price1") != null)
            {
                var price1 = contextAccessor.HttpContext.Session.GetString("price1");
                var price2 = contextAccessor.HttpContext.Session.GetString("price2");
                var address = contextAccessor.HttpContext.Session.GetString("address");
                List<FootBallFieldModel> pitchTemp = _context.FootBallFields.ToList();
                List<FootBallFieldModel> pitch1 = new List<FootBallFieldModel>();
                foreach (var item in pitchTemp)
                {
                    if (item.Address.Contains(address))
                    {
                        if (item.Gia >= float.Parse(price1) && item.Gia <= float.Parse(price2))
                        {
                            pitch1.Add(item);
                        }
                    }
                }
                foreach (FootBallFieldModel field in pitch1)
                {
                    field.ListField = _context.listFields.Where(i => i.IDFootballField == field.IDFootBallField).ToList();
                    field.ratings = _context.Ratings.Where(i => i.IDField == field.IDFootBallField).ToList();
                }
                var getUserId1 = _userManager.GetUserAsync(HttpContext.User);
                if (getUserId1.Result == null) return View("ListPitchComponent", pitch1);
                ViewBag.ListFieldLike = _context.FieldLike.Where(i => i.Username == getUserId1.Result.Id).ToList();
                contextAccessor.HttpContext.Session.Remove("price1");
                contextAccessor.HttpContext.Session.Remove("price2");
                contextAccessor.HttpContext.Session.Remove("address");
                return View(pitch1);
            }
            var pitch = _context.FootBallFields.Where(i => i.isDisable == 0).ToList();
            foreach (FootBallFieldModel field in pitch)
            {
                field.ListField = _context.listFields.Where(i => i.IDFootballField == field.IDFootBallField).ToList();
                field.ratings = _context.Ratings.Where(i => i.IDField == field.IDFootBallField).ToList();
            }
            var getUserId = _userManager.GetUserAsync(HttpContext.User);
            if (getUserId.Result == null) return View("Index", pitch);
            ViewBag.ListFieldLike = _context.FieldLike.Where(i => i.Username == getUserId.Result.Id).ToList();
            return View(pitch);
        }
        [Authorize(Roles = "Admin,Partner,User")]
        public IActionResult DatSan(string idField)
        {
            var pitch = _context.listFields.FirstOrDefault(f => f.IDField == idField);
            pitch.FootBall = _context.FootBallFields.Where(f => f.IDFootBallField == pitch.IDFootballField).FirstOrDefault();
            return View(pitch);
        }
        [Authorize(Roles = "Admin,Partner,User")]
        public IActionResult DS(string id)
        {
            var field = _context.FootBallFields.FirstOrDefault(i => i.IDFootBallField == id && i.isDisable == 0);
            if (field != null)
            {
                field.ListField = _context.listFields.Where(i => i.IDFootballField.Equals(field.IDFootBallField)).ToList();
                foreach(ListFieldModel fields in field.ListField)
                {
                    fields.Type = _context.TypeFields.FirstOrDefault(i => i.IDType == fields.IDType);
                }
                field.ratings = _context.Ratings.Where(i => i.IDField == field.IDFootBallField).ToList();
                foreach (RatingModel rate in field.ratings)
                {
                    rate.User = _context.User.FirstOrDefault(i => i.Id == rate.Username);
                }
                field.ratings.OrderByDescending(i => i.Diem).ToList();
                
                return View(field);
            }
            return NotFound();
        }
        [Authorize(Roles = "Admin,Partner,User")]
        [HttpPost]
        public async Task<IActionResult> DatSanConfirm(String id, String emailUser, String Username, String SDT, String BeginTime, DateTime Date, String idParentField)
        {
            
            TimeSpan timeCurrent = DateTime.Parse(BeginTime).TimeOfDay;
            DateTime futureTime = DateTime.Parse(BeginTime).AddHours(1).AddMinutes(30);
            TimeSpan timeDiff = timeCurrent - DateTime.Now.TimeOfDay;

            if (timeCurrent.Hours >= 21 || futureTime.Hour >= 21 || timeCurrent.Hours <= 7)
            {
                TempData["LoiDatSan"] = "Quá giờ đặt sân";
                var pitch = _context.listFields.FirstOrDefault(f => f.IDField == id);
                pitch.FootBall = _context.FootBallFields.Where(f => f.IDFootBallField == pitch.IDFootballField).FirstOrDefault();
                return View("DatSan", pitch);
            }else if (Math.Abs(timeDiff.TotalMinutes) <= 30)
            {
                TempData["LoiDatSan"] = "Giờ đặt sân không hợp lệ vui lòng đặt sân sớm hơn 30 phút";
                var pitch = _context.listFields.FirstOrDefault(f => f.IDField == id);
                pitch.FootBall = _context.FootBallFields.Where(f => f.IDFootBallField == pitch.IDFootballField).FirstOrDefault();
                return View("DatSan", pitch);
            }
            var getIDOrder = _context.OrderField.Where(i => i.IDFootballField == idParentField && i.IDChildField == id).Select(i => i.IDOrder).ToList();
            if (getIDOrder != null) {
                foreach (var IdOrder in getIDOrder)
                {
                    var find = _context.DetailsOrder.FirstOrDefault(i => i.IDOrder == IdOrder);
                    if (find.DateTime == Date && find.Status == "Đang Đến")
                    {
                        var getBeforeBegin = DateTime.Parse(find.StartTime).AddHours(-1).AddMinutes(-30).TimeOfDay;
                        var getAfterBegin = DateTime.Parse(find.StartTime).AddHours(1).AddMinutes(30).TimeOfDay;
                        if ((timeCurrent < getAfterBegin && timeCurrent > getBeforeBegin) || (DateTime.Parse(BeginTime) == DateTime.Parse(find.StartTime)) || DateTime.Parse(BeginTime) >= DateTime.Parse(find.StartTime) && DateTime.Parse(BeginTime) <= DateTime.Parse(find.StartTime).AddHours(1).AddMinutes(30))
                        {
                            TempData["LoiDatSan"] = "Giờ Đặt Sân Không Hợp Lệ, Đã có người đặt sân trong khung giờ này";
                            var pitch = _context.listFields.FirstOrDefault(f => f.IDField == id);
                            pitch.FootBall = _context.FootBallFields.Where(f => f.IDFootBallField == pitch.IDFootballField).FirstOrDefault();
                            return View("DatSan", pitch);
                        }
                    }
                    else continue;
                }
            }
            OrderFieldModel order = new OrderFieldModel();
            order.IDOrder = Guid.NewGuid().ToString();
            order.IDFootballField = idParentField;
            order.IDUser = _userManager.FindByNameAsync(emailUser).Result.Id;
            order.SoDienThoai = SDT;
            order.IDChildField = id;


            DetailsOrderModel details = new DetailsOrderModel();
            details.IDOrder = order.IDOrder;
            details.IDDetails = Guid.NewGuid().ToString();
            details.StartTime = BeginTime; 
            details.DateTime = Date;
            details.Status = "Đang Đến";



            HistoryOrderModel history = new HistoryOrderModel();
            history.IDDetails = details.IDDetails;
            history.Username = Username;
            history.IDHistory = Guid.NewGuid().ToString();
            history.IDUser = _userManager.FindByNameAsync(User.Identity.Name).Result.Id;

            _context.OrderField.Add(order);
            _context.DetailsOrder.Add(details);
            _context.HistoryOrders.Add(history);

            _context.SaveChanges();
            return View("Thanks", details);
        }
        public IActionResult CancelOrder(string id)
        {
            var order = _context.DetailsOrder.FirstOrDefault(i => i.IDOrder == id);
            DateTime startTime = DateTime.Parse(order.StartTime);
            DateTime currentTime = DateTime.Now;
            TimeSpan timeDifference = startTime -  currentTime ;
            if (timeDifference.TotalMinutes <= 30 && timeDifference.TotalMinutes >= 0)
            {
                return Content("Quá thời gian hủy sân");
            }
            else
            {
                order.Status = "Đã Hủy";
                var getUser = _userManager.GetUserAsync(HttpContext.User).Result;
                if (getUser == null)
                {
                    return RedirectToAction("Index", "Home");
                }
                _context.DetailsOrder.Update(order);
                _context.SaveChanges();
                List<HistoryOrderModel> hisOrder = _context.HistoryOrders.Where(i => i.IDUser == getUser.Id).ToList();

Soccer_Care/Views/Shared/_Layout.cshtml
@inject IHttpContextAccessor accessor
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <title>Soccer Care</title>


    <!--Dropdown-->
    <!-- Bootstrap core CSS -->
    <link href="/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/css/main.css" />
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="/assets/css/fontawesome.css">
    <link rel="stylesheet" href="/assets/css/templatemo-plot-listing.css">
    <link rel="stylesheet" href="/assets/css/animated.css">
    <link rel="stylesheet" href="/assets/css/owl.css">
    <link rel="stylesheet" href="/assets/css/drop.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
</head>

<body>

    <!-- ***** Preloader Start ***** -->
    <div id="js-preloader" class="js-preloader">
        <div class="preloader-inner">
            <span class="dot"></span>
            <div class="dots">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>
    </div>

    <!-- ***** Preloader End ***** -->
    <!-- ***** Header Area Start ***** -->
    <header class="header-area header-sticky wow slideInDown" data-wow-duration="0.75s" data-wow-delay="0s">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <nav class="main-nav">
                        <!-- ***** Logo Start ***** -->
                        <a asp-controller="Home" asp-action="Index" class="logo"></a>
                        <!-- ***** Logo End ***** -->
                        <!-- ***** Menu Start ***** -->
                        <ul class="nav d-flex align-items-start">
                            <li><a asp-controller="Home" asp-action="Index">Trang chủ</a></li>
                            <li><a asp-controller="PitchBall" asp-action="Index">Sân bóng</a></li>
                            <li><a asp-controller="Home" asp-action="Intro">Giới thiệu</a></li>
                            <li><a asp-controller="Contact" asp-action="Index">Liên hệ</a></li>
                            <li class="mb-8"><partial name="_LoginPartial.cshtml"></partial></li>
                        </ul>
                        <a class='menu-trigger'>
                            <span>Menu</span>
                        </a>
                        <!-- ***** Menu End ***** -->
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <partial name="/Views/Shared/_Notification.cshtml" />
    @RenderBody()

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-4">
                    <div class="about">
                        <div class="logo">
                            <img src="/assets/images/soccer_care1.svg" height="150" alt="Plot Listing">
                        </div>
                        <p>
                            Dịch vụ đặt sân bóng mini mang lại sự tiện lợi và thú vị cho người chơi yêu thích bóng đá và các môn thể thao khác. 
                            
                        </p>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="helpful-links">
                        <h4>Tiện ích</h4>
                        <div class="row">
                            <div class="col-lg-6 col-sm-6">
                                <ul>
                                    <li><a href="#">Danh mục</a></li>
                                    <li><a href="#">Đánh giá</a></li>
                                    <li><a href="#">Dịch vụ</a></li>
                                    <li><a href="#">Liên hệ</a></li>
                                </ul>
                            </div>
                            <div class="col-lg-6">
                                <ul>
                                    <li><a href="#">Chính sách</a></li>
                                    <li><a href="#">Thưởng</a></li>
                                    <li><a href="#">Hội viên</a></li>
                                    <li><a href="#">VN Pay</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="contact-us">
                        <h4>Liên hệ</h4>
                        <p>Khu Công nghệ cao, Thành Phố Hồ Chí Minh</p>
                        <div class="row">
                            <div class="col-lg-6">
                                <a href="#">010-020-0340</a>
                            </div>
                            <div class="col-lg-6">
                                <a href="#">090-080-0760</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="sub-footer">
                        <p>
                            Copyright © 2024 by ...
                           
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </footer>


    <!-- Scripts -->
    <script src="/vendor/jquery/jquery.min.js"></script>
    <script src="/assets/js/owl-carousel.js"></script>
    <script src="/assets/js/animation.js"></script>
    <script src="/assets/js/imagesloaded.js"></script>
    <script src="/assets/js/custom.js"></script>

    <script>
        function myFunction() {
            document.getElementById("myDropdown").classList.toggle("show");
        }

        // Close the dropdown menu if the user clicks outside of it
        window.onclick = function (event) {
            if (!event.target.matches('.dropbtn')) {
                var dropdowns = document.getElementsByClassName("dropdown-content");
                var i;
                for (i = 0; i < dropdowns.length; i++) {
                    var openDropdown = dropdowns[i];
                    if (openDropdown.classList.contains('show')) {
                        openDropdown.classList.remove('show');
                    }
                }
            }
        }
    </script>

</body>

</html>

Soccer_Care/Views/Shared/_LayoutDS.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <title>Soccer Care</title>
    <link href="/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/assets/css/fontawesome.css">
    <link rel="stylesheet" href="/assets/css/templatemo-plot-listing.css">
    <link rel="stylesheet" href="/assets/css/animated.css">
    <link rel="stylesheet" href="/assets/css/owl.css">
    <link rel="stylesheet" href="/assets/css/drop.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />

    <link rel="stylesheet" href="/css/main.css">




</head>

<body class="w-main">

    <!-- ***** Preloader Start ***** -->
    <div id="js-preloader" class="js-preloader">
        <div class="preloader-inner">
            <span class="dot"></span>
            <div class="dots">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>
    </div>
    <partial name="/Views/Shared/_Notification.cshtml" />

    @RenderBody()



    <script src="/vendor/jquery/jquery.min.js"></script>
    <script src="/assets/js/owl-carousel.js"></script>
    <script src="/assets/js/animation.js"></script>
    <script src="/assets/js/imagesloaded.js"></script>
    <script src="/assets/js/custom.js"></script>
</body>

</html>

Soccer_Care/Views/Shared/_LayoutEmpty.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <title>Soccer Care</title>
    <link href="/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <link rel="stylesheet" href="/assets/css/login.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />


</head>

<body>

    <!-- ***** Preloader Start ***** -->
    <div id="js-preloader" class="js-preloader">
        <div class="preloader-inner">
            <span class="dot"></span>
            <div class="dots">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>
    </div>
    <partial name="/Views/Shared/_Notification.cshtml" />
    @RenderBody()


</body>

</html>

Soccer_Care/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <title>Soccer Care</title>
    <link href="/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <link rel="stylesheet" href="/assets/css/login.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    

</head>

<body>

    <!-- ***** Preloader Start ***** -->
    <div id="js-preloader" class="js-preloader">
        <div class="preloader-inner">
            <span class="dot"></span>
            <div class="dots">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>
    </div>
    <partial name="/Views/Shared/_Notification.cshtml"/>
    @RenderBody()


</body>

</html>

Soccer_Care/Views/Shared/_Notification.cshtml
@inject IHttpContextAccessor httpContext
@if(TempData["SuccessRegister"] != null)
{
    <script src="/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["SuccessRegister"]')
    </script>
}
@if (TempData["FailRegister"] != null)
{
    <script src="/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["FailRegister"]')
    </script>
}
@if (httpContext.HttpContext.Session.GetString("SuccessLogin") != null)
{
    <script src="/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@httpContext.HttpContext.Session.GetString("SuccessLogin")')
    </script>
    httpContext.HttpContext.Session.Remove("SuccessLogin");
}
@if (httpContext.HttpContext.Session.GetString("SuccessEdit") != null)
{
    <script src="/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@httpContext.HttpContext.Session.GetString("SuccessEdit")')
    </script>
    httpContext.HttpContext.Session.Remove("SuccessEdit");
}
@if (TempData["LoginFail"] != null)
{
    <script src="/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["LoginFail"]')
    </script>
}
@if (TempData["EditSuccess"] != null)
{
    <script src="/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["EditSuccess"]')
    </script>
}
@if (TempData["CommentSuccess"] != null)
{
    <script src="/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["CommentSuccess"]')
    </script>
}
@if (TempData["LoiDatSan"] != null)
{
    <script src="/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["LoiDatSan"]')
    </script>
}